import '@/components/Accordions/Accordions.makeswift'
import '@/components/Button/Button.makeswift'
import '@/components/Footer/Footer.makeswift'
import '@/components/Marquee/Marquee.makeswift'
import '@/components/Navigation/Navigation.makeswift'
import '@/components/Tabs/Tabs.makeswift'
